<?xml version="1.0" ?>
<!-- =================================================================================== -->
<!-- |    This document was autogenerated by xacro from panda_arm_hand.urdf.xacro      | -->
<!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                                 | -->
<!-- =================================================================================== -->


<robot name="shelf" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name="side_length" value="1.25" />
<xacro:property name="wall_width" value=".025" />
<xacro:property name="depth" value=".3" />
<xacro:property name="side_offset" value="${side_length/2-wall_width/2}" />


<xacro:macro name="side_shape">
    <geometry>
        <box size="${depth} ${side_length} ${wall_width}"/>
      </geometry>
</xacro:macro>

<xacro:macro name="back_shape">
    <geometry>
        <box size="${side_length} ${side_length} ${wall_width}"/>
      </geometry>
</xacro:macro>

  <link name="center"/>

  <link name="back">
    <visual>
      <xacro:back_shape />
      <material name="back"/>
    </visual>
    <collision>
      <xacro:back_shape />
      <material name="back"/>
    </collision>
  </link>

  <link name="right">
    <visual>
      <xacro:side_shape />
      <material name="side"/>
    </visual>
    <collision>
      <xacro:side_shape />
      <material name="side"/>
    </collision>
  </link>

  <link name="left">
  <visual>
    <xacro:side_shape />
    <material name="side"/>
  </visual>
  <collision>
    <xacro:side_shape />
    <material name="side"/>
  </collision>
  </link>

  <link name="bottom">
  <visual>
    <xacro:side_shape />
    <material name="side"/>
  </visual>
  <collision>
    <xacro:side_shape />
    <material name="side"/>
  </collision>
  </link>

  <link name="top">
  <visual>
    <xacro:side_shape />
    <material name="side"/>
  </visual>
  <collision>
    <xacro:side_shape />
    <material name="side"/>
  </collision>
  </link>


  <joint name="center_base_joint" type="fixed">
    <parent link="center"/>
    <child link="back"/>
    <origin xyz="0 0 ${-depth/2}" rpy="0 1.5708 0"/>
  </joint> 

  <joint name="right_joint" type="fixed">
    <parent link="back"/>
    <child link="right"/>
    <origin xyz="0 ${side_offset} ${depth/2}" rpy="1.5708 1.5708 0 "/>
  </joint>

   <joint name="left_joint" type="fixed">
    <parent link="back"/>
    <child link="left"/>
    <origin xyz="0 ${-side_offset} ${depth/2}" rpy="1.5708 1.5708 0 "/>
  </joint>

   <joint name="bottom_joint" type="fixed">
    <parent link="back"/>
    <child link="bottom"/>
    <origin xyz="${side_offset}  0 ${depth/2}" rpy="0 1.5708 0 "/>
  </joint>

   <joint name="top_joint" type="fixed">
    <parent link="back"/>
    <child link="top"/>
    <origin xyz="${-side_offset} 0 ${depth/2}" rpy="0 1.5708 0 "/>
  </joint>

  <material name="back">
    <color rgba="1. 1. 1. 1."/>
  </material>

    <material name="side">
    <color rgba=".4 .4 .4 1."/>
  </material>
 </robot>
